/* Texte der Oberfläche. Schlüssel = deutscher Text oder Kurzname; EN daneben. */
window.TEXTE = {
  de: {
    update_titel: "Updates automatisch installieren",
    update_text: "Neue Fassungen kommen von deinem Server und werden installiert, sobald der Worker nichts zu tun hat.",
    app_update_auto: "Wird automatisch installiert, sobald der Worker frei ist.",
    app_update_laden: "Wird geladen … {prozent}", app_update_installieren: "Wird installiert – der Worker startet gleich neu.",
    app_update_fehler: "Update fehlgeschlagen: {fehler}", app_update_hand: "Bitte die neue Fassung von der Taleward-Website installieren.",
    regler_titel: "Grafikspeicher für Taleward",
    regler_text: "Höchstens so viel nutzt der Worker. Der Rest bleibt frei für Spiele und andere Programme.",
    regler_alles: "Alles", regler_von: "{a} von {b}",
    prozessor_titel: "Nur den Prozessor verwenden",
    prozessor_text: "Lässt die Grafikkarte ganz frei. Dauert deutlich länger.",
    pw_gpu: "Grafikkarte · {modell}", pw_gpu_teil: "Grafikkarte · {modell} · Ausrichtung und Sprechertrennung auf dem Prozessor",
    pw_cpu: "Prozessor · {modell}", pw_grenze: "höchstens {gb}",
    pw_dauer: "Eine 4-Stunden-Aufnahme dauert etwa {dauer} (grobe Schätzung).",
    pw_genau: "genau", pw_schnell: "schneller, etwas ungenauer",
    dauer_min: "{a}–{b} Minuten", dauer_std: "{a}–{b} Stunden",
    messung_text: "{audio} Aufnahme in {rechen}", messung_peak: "höchstens {gb} Grafikspeicher",
    noch_keine_messung: "noch kein Auftrag",
    neustart_offen: "Wird nach dem laufenden Auftrag übernommen.",
    pr_gpu_keine_cpu: "Keine nutzbare NVIDIA-Grafikkarte gefunden.",
    pr_gpu_klein: "{name} · {vram} – zu wenig Grafikspeicher, der Worker nutzt den Prozessor.",
    pr_ram: "Arbeitsspeicher", pr_ram_text: "{gb} GB", pr_ram_wenig: "{gb} GB – empfohlen sind mindestens {min} GB.",
    pr_arbeitsweise: "Arbeitsweise",
    pr_cpu_angebot: "Der Worker kann mit dem Prozessor arbeiten. Das dauert deutlich länger – eine 4-Stunden-Aufnahme etwa 4 bis 10 Stunden –, läuft aber gut über Nacht. Zum reinen Ausprobieren gibt es den Testmodus.",
    installieren_text_cpu: "Einmalig etwa {mb} herunterladen (Fassung für den Prozessor, ohne Grafikkarten-Bibliotheken).",
    intro_verbinden: "Dieser PC übernimmt für deinen Taleward-Server die Transkription der Aufnahmen. Sie werden hier verarbeitet und danach gelöscht – nichts bleibt auf diesem PC liegen.",
    hilfe_code: "In der Verwaltung des Servers: Transkription → Weiteren Worker anbinden → Kopplungscode erzeugen. Der Code gilt 15 Minuten.",
    hilfe_name: "So erscheint dieser PC in der Verwaltung.",
    unsicher_erlauben: "Unverschlüsselt verbinden – nur im eigenen Heimnetz (die Adresse beginnt mit http://).",
    inst_punkt_1: "Python und die KI-Bibliotheken (WhisperX, PyTorch für deine Grafikkarte)",
    inst_punkt_2: "Den Taleward-Worker in genau der Fassung deines Servers",
    inst_punkt_3: "Später beim ersten Auftrag: die Sprachmodelle (einmalig etwa 5 GB)",
    installieren_text_windows: "Einmalig etwa {mb} herunterladen. Je nach Internet dauert das 10 bis 30 Minuten – du kannst den PC in der Zeit normal nutzen.",
    installieren_text_test: "Im Testmodus reichen ein paar MB: Der Worker schreibt Platzhaltertext statt einer echten Transkription.",
    fertig_text: "Der Worker holt sich ab jetzt selbst neue Aufnahmen vom Server. Du musst nichts weiter tun.",
    autostart_titel: "Mit dem Computer starten",
    autostart_text: "Startet unsichtbar im Hintergrund, sobald du dich anmeldest.",
    hintergrund_titel: "Beim Schließen weiterlaufen",
    hintergrund_text: "Das Fenster verschwindet, der Worker arbeitet weiter. Symbol im Infobereich.",
    hinweis_erste_modelle: "Beim ersten Start lädt der Worker die Sprachmodelle (einmalig etwa 5 GB). Danach geht es sofort los.",
    modell_titel: "Sprachmodell",
    modell_text: "„Automatisch“ wählt nach dem Grafikspeicher.",
    modell_auto: "Automatisch (empfohlen)", modell_genau: "Genau (large-v3)", modell_schnell: "Schnell (large-v3-turbo)",
    gefahr_text: "Neu koppeln, wenn der Server neu eingerichtet wurde. Das KI-Paket und die Modelle belegen die meisten GB – entfernen gibt den Platz frei.",
    // Zustände
    st_warte: "Bereit", st_warte_text: "Wartet auf neue Aufnahmen von {server}.",
    st_arbeitet: "Arbeitet", st_transcribe: "Transkription einer Aufnahme", st_voice_enroll: "Stimmprofil wird angelernt",
    st_summarize: "Zusammenfassung mit lokalem Sprachmodell", st_document: "Unterlage wird ausgewertet",
    st_pausiert: "Pausiert", st_pausiert_text: "Nimmt keine neuen Aufnahmen an. Aufträge warten auf dem Server.",
    st_startet: "Startet …", st_startet_text: "Grafikkarte und Modelle werden geprüft.",
    st_modelle_text: "Sprachmodelle werden vorbereitet – beim ersten Start einmalig etwa 5 GB. Bisher {mb}.",
    st_getrennt: "Keine Verbindung", st_getrennt_text: "Der Server ist gerade nicht erreichbar. Neuer Versuch {wann}.",
    st_fehler: "Braucht deine Hilfe", st_abgelehnt: "Nicht mehr gekoppelt",
    st_abgelehnt_text: "Der Server kennt diesen Worker nicht mehr (in der Verwaltung entfernt oder gesperrt). Bitte neu koppeln.",
    st_abgestuerzt: "Startet neu", st_abgestuerzt_text: "Der Worker wurde unerwartet beendet und startet {wann} neu.",
    st_gestoppt: "Angehalten", st_gestoppt_text: "Der Worker ist aus. Aufträge warten auf dem Server.",
    st_update: "KI-Paket wird aktualisiert", st_update_text: "Der Server läuft jetzt mit Fassung {fassung}. Der Worker lädt die passende Fassung ({prozent}) und wechselt danach selbst.",
    app_update: "Neue Fassung der Worker-App: {version}.",
    neuer_versuch_in: "in {s} s", gleich: "gleich",
    laufzeit: "seit {min} min",
    // Prüfung
    pr_gpu: "Grafikkarte", pr_gpu_keine: "Keine NVIDIA-Grafikkarte gefunden. Der Worker braucht eine NVIDIA-Karte mit mindestens 6 GB Grafikspeicher.",
    pr_treiber: "Treiber", pr_treiber_alt: "Treiber {v} ist zu alt – bitte mindestens {min} installieren (NVIDIA-App oder nvidia.com).",
    pr_platz: "Speicherplatz", pr_platz_text: "{frei} GB frei, gebraucht werden etwa {noetig} GB.",
    pr_modell: "Sprachmodell", pr_modell_text: "{modell} – passend für {vram} Grafikspeicher.",
    pr_nicht_bereit: "Dieser PC kann so keine Aufnahmen verarbeiten. Zum Ausprobieren gibt es den Testmodus (Platzhaltertext statt Transkription).",
    verbunden_mit: "Verbunden mit {server} als „{name}“.",
    // Installation
    ph_start: "Vorbereiten …", ph_python: "Python wird eingerichtet", ph_pakete: "KI-Bibliotheken werden geladen",
    ph_taleward: "Taleward-Worker wird installiert", ph_ffmpeg: "Letzte Prüfung", ph_fertig: "Fertig",
    mb_von: "{a} von etwa {b}",
    // Fehler
    f_adresse_leer: "Bitte die Adresse des Servers eintragen.",
    f_adresse_ungueltig: "Diese Adresse ist ungültig.",
    f_nicht_erreichbar: "Der Server ist nicht erreichbar. Adresse prüfen – steht sie so auch in der App?",
    f_zeitueberschreitung: "Der Server antwortet nicht. Später erneut versuchen.",
    f_kein_taleward: "Unter dieser Adresse läuft kein Taleward-Server.",
    f_https_umleitung: "Der Server leitet auf https:// um – bitte die Adresse mit https:// eintragen.",
    f_unverschluesselt: "Die Adresse ist unverschlüsselt (http://). Nur im eigenen Heimnetz erlauben – Haken unten setzen.",
    f_code_fehlt: "Bitte den Kopplungscode eintragen.",
    f_koppeln_fehlgeschlagen: "Koppeln hat nicht geklappt.",
    f_uv_fehlt: "Ein Bestandteil der App fehlt (uv). Bitte die App neu installieren.",
    f_github_nicht_erreichbar: "Der Download-Server (GitHub) ist nicht erreichbar. Internetverbindung prüfen.",
    f_netz: "Der Download ist abgebrochen. Internetverbindung prüfen und erneut versuchen – bereits Geladenes wird dabei nicht wiederverwendet.",
    f_kein_platz: "Nicht genug Speicherplatz. Etwas Platz schaffen und erneut versuchen.",
    f_installation: "Die Installation ist fehlgeschlagen. Im Protokoll steht, woran es lag.",
    f_ffmpeg: "ffmpeg konnte nicht eingerichtet werden.",
    f_unerwartet: "Unerwarteter Fehler bei der Installation.",
    f_abgebrochen: "Installation abgebrochen.",
    f_motor_fehlt: "Das KI-Paket ist nicht installiert.",
    f_start_fehlgeschlagen: "Der Worker ließ sich nicht starten.",
    f_einrichtung: "Der Worker kann nicht starten.",
    bestaetigen_entfernen: "KI-Paket und Sprachmodelle wirklich entfernen? Der Worker verarbeitet dann nichts mehr, bis du neu installierst.",
    bestaetigen_koppeln: "Neu koppeln? Du brauchst dafür einen neuen Kopplungscode aus der Verwaltung.",
    kopiert: "Protokoll kopiert.",
    hintergrund_hinweis: "Der Worker läuft im Hintergrund weiter – das Symbol findest du im Infobereich.",
    speicher_text: "KI-Paket {motor}, Sprachmodelle {modelle}.",
    testmodus_aktiv: "Testmodus",
    fassung_text: "App {app} · KI-Paket {motor}",
  },
  en: {
    "Status": "Status", "Einstellungen": "Settings", "Protokoll": "Log", "Verbinden": "Connect", "Prüfen": "Check",
    "Installieren": "Install", "Fertig": "Done", "Worker einrichten": "Set up worker", "Adresse des Servers": "Server address",
    "Kopplungscode": "Pairing code", "Name dieses Workers": "Name of this worker", "Diesen PC prüfen": "Checking this PC",
    "Erneut prüfen": "Check again", "Im Testmodus einrichten": "Set up in test mode", "Weiter": "Continue",
    "KI-Paket laden": "Download AI package", "Abbrechen": "Cancel", "Protokoll ansehen": "View log",
    "Erneut versuchen": "Try again", "Fertig eingerichtet": "All set", "Worker starten": "Start worker",
    "Heute verarbeitet": "Processed today", "Insgesamt": "Total", "Server": "Server", "Worker-Name": "Worker name",
    "Grafikkarte": "Graphics card", "Sprachmodell": "Speech model", "Fassung": "Version", "Sprache": "Language",
    "Wie das System": "Same as system", "Speicherplatz": "Disk space", "Ordner öffnen": "Open folder",
    "Verwaltung öffnen": "Open admin", "Verbindung und KI-Paket": "Connection and AI package", "Neu koppeln": "Pair again",
    "KI-Paket neu installieren": "Reinstall AI package", "KI-Paket und Modelle entfernen": "Remove AI package and models",
    "Worker beenden": "Quit worker", "Kopieren": "Copy", "Zurück": "Back", "Pausieren": "Pause", "Fortsetzen": "Resume",
    "Starten": "Start", "Anhalten": "Stop", "Jetzt aktualisieren": "Update now", "Herunterladen": "Download",
    update_titel: "Install updates automatically",
    update_text: "New versions come from your server and are installed as soon as the worker has nothing to do.",
    app_update_auto: "Will be installed automatically as soon as the worker is free.",
    app_update_laden: "Downloading … {prozent}", app_update_installieren: "Installing – the worker restarts in a moment.",
    app_update_fehler: "Update failed: {fehler}", app_update_hand: "Please install the new version from the Taleward website.",
    "Jetzt aktualisieren": "Update now", "Was ist neu?": "What's new?",
    regler_titel: "Graphics memory for Taleward",
    regler_text: "The worker uses at most this much. The rest stays free for games and other programs.",
    regler_alles: "All", regler_von: "{a} of {b}",
    prozessor_titel: "Use the processor only",
    prozessor_text: "Leaves the graphics card completely free. Takes considerably longer.",
    pw_gpu: "Graphics card · {modell}", pw_gpu_teil: "Graphics card · {modell} · alignment and speaker separation on the processor",
    pw_cpu: "Processor · {modell}", pw_grenze: "at most {gb}",
    pw_dauer: "A 4-hour recording takes about {dauer} (rough estimate).",
    pw_genau: "accurate", pw_schnell: "faster, slightly less accurate",
    dauer_min: "{a}–{b} minutes", dauer_std: "{a}–{b} hours",
    messung_text: "{audio} of recording in {rechen}", messung_peak: "at most {gb} graphics memory",
    noch_keine_messung: "no job yet",
    neustart_offen: "Takes effect after the current job.",
    pr_gpu_keine_cpu: "No usable NVIDIA graphics card found.",
    pr_gpu_klein: "{name} · {vram} – not enough graphics memory, the worker uses the processor.",
    pr_ram: "Memory (RAM)", pr_ram_text: "{gb} GB", pr_ram_wenig: "{gb} GB – at least {min} GB recommended.",
    pr_arbeitsweise: "How it works",
    pr_cpu_angebot: "The worker can run on the processor. That takes considerably longer – about 4 to 10 hours for a 4-hour recording – but works well overnight. For just trying things out there is test mode.",
    installieren_text_cpu: "About {mb} to download, once (processor version, without graphics card libraries).",
    "Mit dem Prozessor einrichten": "Set up with the processor", "Testmodus": "Test mode", "Arbeitsweise": "How it works", "Gemessen": "Last measured",
    intro_verbinden: "This PC transcribes recordings for your Taleward server. They are processed here and deleted afterwards – nothing stays on this PC.",
    hilfe_code: "In the server's admin: Transcription → Connect another worker → Create pairing code. The code is valid for 15 minutes.",
    hilfe_name: "This is how this PC appears in the admin.",
    unsicher_erlauben: "Connect without encryption – only on your own home network (the address starts with http://).",
    inst_punkt_1: "Python and the AI libraries (WhisperX, PyTorch for your graphics card)",
    inst_punkt_2: "The Taleward worker in exactly your server's version",
    inst_punkt_3: "Later, on the first job: the speech models (about 5 GB, once)",
    installieren_text_windows: "About {mb} to download, once. Depending on your connection this takes 10 to 30 minutes – you can keep using the PC meanwhile.",
    installieren_text_test: "Test mode needs only a few MB: the worker writes placeholder text instead of a real transcript.",
    fertig_text: "From now on the worker fetches new recordings from the server by itself. Nothing else to do.",
    autostart_titel: "Start with the computer", autostart_text: "Starts invisibly in the background when you sign in.",
    hintergrund_titel: "Keep running when closed", hintergrund_text: "The window disappears, the worker keeps working. Icon in the notification area.",
    hinweis_erste_modelle: "On first start the worker downloads the speech models (about 5 GB, once). After that it starts right away.",
    modell_titel: "Speech model", modell_text: "“Automatic” picks by graphics memory.",
    modell_auto: "Automatic (recommended)", modell_genau: "Accurate (large-v3)", modell_schnell: "Fast (large-v3-turbo)",
    gefahr_text: "Pair again if the server was set up anew. The AI package and models take most of the space – removing them frees it.",
    st_warte: "Ready", st_warte_text: "Waiting for new recordings from {server}.",
    st_arbeitet: "Working", st_transcribe: "Transcribing a recording", st_voice_enroll: "Learning a voice profile",
    st_summarize: "Summary with local language model", st_document: "Analysing a document",
    st_pausiert: "Paused", st_pausiert_text: "Not accepting new recordings. Jobs wait on the server.",
    st_startet: "Starting …", st_startet_text: "Checking graphics card and models.",
    st_modelle_text: "Preparing speech models – about 5 GB on first start, once. So far {mb}.",
    st_getrennt: "No connection", st_getrennt_text: "The server can't be reached right now. Next try {wann}.",
    st_fehler: "Needs your attention", st_abgelehnt: "No longer paired",
    st_abgelehnt_text: "The server no longer knows this worker (removed or blocked in the admin). Please pair again.",
    st_abgestuerzt: "Restarting", st_abgestuerzt_text: "The worker stopped unexpectedly and restarts {wann}.",
    st_gestoppt: "Stopped", st_gestoppt_text: "The worker is off. Jobs wait on the server.",
    st_update: "Updating AI package", st_update_text: "The server now runs version {fassung}. The worker is downloading the matching version ({prozent}) and switches over by itself.",
    app_update: "New version of the worker app: {version}.",
    neuer_versuch_in: "in {s} s", gleich: "shortly", laufzeit: "for {min} min",
    pr_gpu: "Graphics card", pr_gpu_keine: "No NVIDIA graphics card found. The worker needs an NVIDIA card with at least 6 GB of graphics memory.",
    pr_treiber: "Driver", pr_treiber_alt: "Driver {v} is too old – please install at least {min} (NVIDIA app or nvidia.com).",
    pr_platz: "Disk space", pr_platz_text: "{frei} GB free, about {noetig} GB needed.",
    pr_modell: "Speech model", pr_modell_text: "{modell} – suits {vram} of graphics memory.",
    pr_nicht_bereit: "This PC can't process recordings like this. To try things out there is test mode (placeholder text instead of a transcript).",
    verbunden_mit: "Connected to {server} as “{name}”.",
    ph_start: "Preparing …", ph_python: "Setting up Python", ph_pakete: "Downloading AI libraries",
    ph_taleward: "Installing Taleward worker", ph_ffmpeg: "Final check", ph_fertig: "Done", mb_von: "{a} of about {b}",
    f_adresse_leer: "Please enter the server address.", f_adresse_ungueltig: "This address is invalid.",
    f_nicht_erreichbar: "The server can't be reached. Check the address – is it the same as in the app?",
    f_zeitueberschreitung: "The server doesn't respond. Try again later.", f_kein_taleward: "There is no Taleward server at this address.",
    f_https_umleitung: "The server redirects to https:// – please enter the address with https://.",
    f_unverschluesselt: "The address is unencrypted (http://). Only allow this on your home network – tick the box below.",
    f_code_fehlt: "Please enter the pairing code.", f_koppeln_fehlgeschlagen: "Pairing didn't work.",
    f_uv_fehlt: "Part of the app is missing (uv). Please reinstall the app.",
    f_github_nicht_erreichbar: "The download server (GitHub) can't be reached. Check your internet connection.",
    f_netz: "The download was interrupted. Check your internet connection and try again.",
    f_kein_platz: "Not enough disk space. Free some space and try again.",
    f_installation: "The installation failed. The log shows why.", f_ffmpeg: "ffmpeg could not be set up.",
    f_unerwartet: "Unexpected error during installation.", f_abgebrochen: "Installation cancelled.",
    f_motor_fehlt: "The AI package is not installed.", f_start_fehlgeschlagen: "The worker could not be started.",
    f_einrichtung: "The worker can't start.",
    bestaetigen_entfernen: "Really remove the AI package and speech models? The worker won't process anything until you reinstall.",
    bestaetigen_koppeln: "Pair again? You'll need a new pairing code from the admin.",
    kopiert: "Log copied.", hintergrund_hinweis: "The worker keeps running in the background – find its icon in the notification area.",
    speicher_text: "AI package {motor}, speech models {modelle}.", testmodus_aktiv: "Test mode",
    fassung_text: "App {app} · AI package {motor}",
  },
};
